# roles/trivy/tasks/main.yml
---
- name: Update apt cache for Trivy repository
  ansible.builtin.apt:
    update_cache: yes
  tags:
    - trivy
    - apt

- name: Install prerequisites for Trivy (wget, apt-transport-https, gnupg2)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - apt-transport-https
    - gnupg2
  tags:
    - trivy
    - apt

- name: Create /usr/local/share/keyrings directory for Trivy GPG key
  ansible.builtin.file:
    path: /usr/local/share/keyrings
    state: directory
    mode: '0755'
  tags:
    - trivy

- name: Download and add Trivy GPG key
  ansible.builtin.shell: |
    wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/local/share/keyrings/trivy.gpg > /dev/null
  args:
    creates: /usr/local/share/keyrings/trivy.gpg # Only run if the key isn't already there
  tags:
    - trivy

- name: Add Trivy repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/local/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb {{ ansible_distribution_codename }} main"
    state: present
    update_cache: yes # Update cache after adding repo
  tags:
    - trivy
    - apt

- name: Install Trivy
  ansible.builtin.apt:
    name: trivy
    state: present
  tags:
    - trivy